format = """$os$directory$git_branch$git_status$c$python$nodejs$rust$golang$dart$character"""

# Disable the blank line at the start of the prompt
add_newline = false

# # Set 'foo' as custom color palette
# palette = 'foo'

# # Define custom colors
# [palettes.foo]
# # Overwrite existing color
# blue = '21'
# mustard = '#af8700'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[os]
disabled = true
style = 'bold white'
format = '[$symbol]($style) '

[os.symbols]
Arch = ' '
Ubuntu = ' '
Debian = ' '
Fedora = ' '
Linux = ' '
Macos = ' '
Windows = '󰍲 '

[package]
disabled = true

[directory]
style = 'bold cyan'
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = ' '
style = 'bold purple'
format = 'on [$symbol$branch(:$remote_branch)]($style) '

[git_commit]
format = '[\($hash$tag\)]($style) '

[git_metrics]
disabled = false
added_style = 'bold green'
deleted_style = 'bold red'
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[git_status]
style = 'bold red'
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = '=${count} '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
untracked = '?${count} '
stashed = '$${count} '
modified = '!${count} '
staged = '+${count} '
renamed = '»${count} '
deleted = '✘${count} '

# [c]
# symbol = ' '
# format = '[$symbol]($style)'
# style = 'blue'
#
# [python]
# symbol = ' '
# format = '[$symbol]($style)'
# style = 'yellow'
#
# [nodejs]
# symbol = ' '
# format = '[$symbol]($style)'
# style = 'green'
#
# [rust]
# symbol = '󱘗 '
# format = '[$symbol]($style)'
# style = 'red'
#
# [golang]
# symbol = ' '
# format = '[$symbol]($style)'
# style = 'cyan'
#
# [dart]
# symbol = ' '
# format = '[$symbol]($style)'
# style = 'blue'
